server:
  port: 9901

spring:
  application:
    name: service-a
  zipkin:
    base-url: http://localhost:9400
    enabled: true
# 注册中心
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 6
    lease-renewal-interval-in-seconds: 6
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/
    registryFetchIntervalSeconds: 6
    registerWithEureka: true
    fetchRegistry: true

feign:
  name: service-b
  provider: service-b
  ##开启Hystrix断路器
  hystrix:
    enabled: true

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000