server:
  port: 8082

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: service-a
        uri: lb://service-a
        predicates:
        - Path=/sva/**
      - id: service-b
        uri: lb://service-b
        predicates:
        - Path=/svb/**

# 注册中心
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 6
    lease-renewal-interval-in-seconds: 6
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/
    registryFetchIntervalSeconds: 6
    registerWithEureka: true
    fetchRegistry: true




